In [1]:
import pandas as pd
import numpy as np

In [5]:
data=np.random.rand(1,1000)
data.min()

0.0005840572017152823

In [16]:
x=np.random.rand(1,5)
y=np.random.rand(1,5)
print(x)
print(y)
cov=np.cov(x,y)
cov_matrix=(np.cov(x,y)[0,1])**2
print(cov)
print(cov_matrix)

[[0.96905816 0.83210688 0.98787084 0.82557324 0.92785238]]
[[0.96191284 0.44579187 0.44640339 0.2989024  0.96224339]]
[[0.00576357 0.01337158]
 [0.01337158 0.09939408]]
0.00017879925342642968


In [3]:
#alpha,reg,t_end = [r2,mape,mse]
metrics_02_55_3 = [0.6094224806591071,0.19176160614567878,0.04066659730087516]   
metrics_02_6_3 = [0.5602845046228879,0.20960294060679505,0.04578280134410097]
metrics_02_7_4 = [-0.0790221678872211,0.3444926985727301,0.1123468653655119]

In [12]:
preds = np.load('C:/Users/EBOZZOL1B/OneDrive - NTT DATA EMEAL/Projects/Git_projects/qml_code/reservoir-computing/v_1.0/Results/Metrics/Predictions_tot_Bloqade_1_3.0_step_run_gen_mode.npy')

In [19]:
a = preds[2]
b = preds[4]
np.save('C:/Users/EBOZZOL1B/OneDrive - NTT DATA EMEAL/Projects/Git_projects/qml_code/reservoir-computing/v_1.0/Results/Metrics/Predictions_1_run_Bloqade_0.3_sec_alpha_0.2_reg_0.55_gen_mode', a) 
np.save('C:/Users/EBOZZOL1B/OneDrive - NTT DATA EMEAL/Projects/Git_projects/qml_code/reservoir-computing/v_1.0/Results/Metrics/Predictions_1_run_Bloqade_0.3_sec_alpha_0.2_reg_0.6_gen_mode', b) 